title: 我的知识库
description: 个人学习和工作笔记整理
author: Your Name
email: your-email@example.com

# 使用 gitbook 主题
theme: jekyll-gitbook
# 或者使用远程主题（如果上面不工作）
# remote_theme: sighingnow/jekyll-gitbook

# 插件
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# GitBook 特定配置
version: "1.0"

# 目录生成配置
toc:
  enabled: true
  h_min: 1
  h_max: 4
  list_class: "section-nav"
  sublist_class: "section-nav"
  item_class: "toc-entry"
  item_prefix: "toc-"

# 搜索功能
search:
  enabled: true
  # 如果使用 Algolia 搜索，在这里配置
  # provider: algolia

# GitBook 样式配置
gitbook:
  # 侧边栏配置
  sidebar:
    logo: "/assets/images/logo.png"  # 可选：添加logo
    search_placeholder: "搜索..."
    
  # 页面配置  
  page:
    # 显示编辑页面链接
    edit_page: true
    # GitHub 仓库信息（用于编辑链接）
    repository_url: "https://github.com/yangyitao/wiki"
    repository_branch: "main"
    
  # 章节导航
  chapter_navigation: true
  
  # 代码主题
  syntax_highlighter: "rouge"
  
  # 数学公式支持
  mathjax: true

# 基本配置
baseurl: ""
url: "https://yangyitao.github.io"

# Markdown 处理
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true

# 默认设置
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "pages"  
    values:
      layout: "default"
      toc: true

# 分页设置
paginate: 10
paginate_path: "/page:num/"

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - xx.sh
  - .DS_Store
  - README.md  # 排除根目录的 README，使用 index.md 作为首页

# 包含文件（确保这些文件被处理）
include:
  - _pages
