title: my-knowledge-base
description: 个人学习和工作笔记整理
author: Your Name
email: your-email@example.com

# 使用 gitbook 主题
remote_theme: sighingnow/jekyll-gitbook

# 插件
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# GitBook 特定配置
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# 默认设置
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

# 导航配置  
toc:
  enabled: true
  h_min: 1
  h_max: 3

# 搜索功能
search:
  enabled: true

# 基本配置
baseurl: ""
url: "https://yangyitao.github.io"

# Markdown 处理
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - setup-gitbook.sh
